services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    restart: always
    depends_on:
      zookeeper:
        condition: service_started
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,EXTERNAL://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: ["CMD", "kafka-broker-api-versions", "--bootstrap-server", "localhost:9092"]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8080:8080"
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      KAFKA_CLUSTERS_0_NAME: local-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092

  ingestion:
    build: .
    restart: always
    depends_on:
      kafka:
        condition: service_healthy
    volumes:
      - .:/app
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    command: python backend/ingestion/subscription_service.py -v

  parquetizer:
    build: .
    restart: always
    depends_on:
      kafka:
        condition: service_healthy
    volumes:
      - .:/app
      - ./data:/app/data
    command: python backend/storage/parquetizer.py -v

  backwards_compress:
      build: .
      restart: always
      depends_on:
        kafka:
          condition: service_healthy
      volumes:
        - .:/app
        - ./data:/app/data
      command: python backend/storage/backwards_compress.py

  analytics:
    build: .
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      kafka:
        condition: service_healthy
    volumes:
      - .:/app
      - ./data:/app/data
    command: uvicorn backend.analytics_server.main:app --host 0.0.0.0 --port 8000

  jupyter:
    build: .
    restart: always
    ports:
      - "127.0.0.1:8888:8888"
    volumes:
      - .:/app
      - ./data:/app/data
    command: start-notebook.sh --NotebookApp.ip='0.0.0.0' --SeverApp.token='' --ServerApp.password=''

    deploy:
      resources:
        limits:
          memory: 5g